services:
  - type: web
    name: argos-ai-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run build && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BINANCE_API_KEY
        scope: secret
      - key: BINANCE_API_SECRET
        scope: secret
      - key: BINANCE_TESTNET_KEY
        scope: secret
      - key: BINANCE_TESTNET_SECRET
        scope: secret
